export interface RuntimePanelData {
  phase: string;
  flow?: string;
  goalSummary?: string | null;
  specPath?: string | null;
  planPath?: string | null;
  milestone?: string | null;
  milestoneText?: string | null;
  milestoneStatus?: string | null;
  nextMilestone?: string | null;
  nextMilestoneText?: string | null;
  milestoneProgress?: string | null;
  milestoneStatusCounts?: string | null;
  taskProgress?: string | null;
  taskStatusCounts?: string | null;
  task?: string | null;
  taskText?: string | null;
  taskStatus?: string | null;
  taskKind?: string | null;
  taskOwner?: string | null;
  expectedOutput?: string | null;
  taskOutputPath?: string | null;
  provider?: string | null;
  modelId?: string | null;
  modelTemperature?: number | null;
  modelMaxTokens?: number | null;
  executionMode?: string | null;
  verifyCommand?: string[] | null;
  recoveryHint?: string | null;
  verificationStatus?: string | null;
  verification?: string | null;
  handoff?: string | null;
  handoffEligible?: boolean;
  handoffReason?: string | null;
  blocker?: string | null;
  resumePhase?: string | null;
  readyTasks?: string[] | null;
  pendingDependencies?: string[] | null;
  allowedTools?: string[] | null;
  recentArtifactSummary?: string | null;
  nextAction?: string | null;
}
